server:
  port: 8081

reactor:
  id: BIOREACTOR-001
  source:
    csv:
      path: ${REACTOR_CSV_PATH:src/main/resources/demo.csv}
      columns: "{'ph': '1AC04 - pH_MV', 'temperature': '1TC01 - Temperature_MV'}"

greycat:
  url: ${GREYCAT_URL:http://greycat:8080}

spring:
  application:
    name: bioreactor-mock-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer