server:
  port: 8081

reactor:
  id: BIOREACTOR-001
  csv:
    path: src/main/resources/demo.csv
    speed-factor: 30

spring:
  application:
    name: bioreactor-mock-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer