version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on: [zookeeper]
    ports: ["9092:9092"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  bioreactor-mock-service:
    build: ./bioreactor-mock-service
    expose: ["8081"]
    depends_on: [kafka]
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  strain-service:
    build: ./strain-service
    expose: ["8085"]

  gateway-service:
    build: ./gateway-service
    ports: ["8086:8086"]
    depends_on: [kafka, bioreactor-mock-service, strain-service]
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      STRAIN_SERVICE_URL:   http://strain-service:8085
      PHYSICAL_SERVICE_URL: http://bioreactor-mock-service:8081
      TWIN_SERVICE_URL:     http://digital-twin-service:8082
      SHADOW_SERVICE_URL:   http://shadow-service:8083
      MODELS_SERVICE_URL:   http://models-service:8084

  models-service:
    build: ./models-service
    expose: ["8084"]
    depends_on: [kafka, strain-service]
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      STRAIN_SERVICE_URL: http://strain-service:8085

  digital-twin-service:
    build: ./digital-twin-service
    expose: ["8082"]
    depends_on: [kafka]
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  shadow-service:
    build: ./shadow-service
    expose: ["8083"]
    depends_on: [kafka]
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_GATEWAY_URL: http://localhost:8086
    ports: ["3000:80"]
    depends_on: [gateway-service]
