server:
  port: 8086

spring:
  application:
    name: gateway-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

services:
  strain-url:     ${STRAIN_SERVICE_URL:http://strain-service:8085}
  physical-url:   ${PHYSICAL_SERVICE_URL:http://bioreactor-mock-service:8081}
  twin-url:       ${TWIN_SERVICE_URL:http://digital-twin-service:8082}
  shadow-url:     ${SHADOW_SERVICE_URL:http://shadow-service:8083}
  models-url:     ${MODELS_SERVICE_URL:http://models-service:8084}
  experiment-url: ${EXPERIMENT_SERVICE_URL:http://experiment-service:8087}